### ISSUE TITLE
nmcli dev wifi command doesn't work

### ISSUE THREAD

**Issue by cjds** [ZachGoldberg/python-nmcli#1]
The error is as below:

 >Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nmcli/nmcli.py", line 100, in run_action
    command=cmd)
  File "/usr/local/lib/python2.7/dist-packages/nmcli/shell.py", line 95, in nmcli
    raise Exception(msg)
Exception: nmcli return 2 code. STDERR='Error: 'dev wifi': invalid field 'TYPE'; allowed fields: SSID,BSSID,MODE,FREQ,RATE,SIGNAL,SECURITY,WPA-FLAGS,RSN-FLAGS,DEVICE,ACTIVE,DBUS-PATH
'

A bunch of other commands fail too. Whatever doesn't conform to the fields specified in `shell.py`

**Comment by cjds** [comment]
Saw the new release made it into pip. Thanks so much :+1: Guess this issue is closed too
