### ISSUE TITLE
cannot import name "nm"

### ISSUE THREAD

**Issue by ryan4volts** [ZachGoldberg/python-nmcli#4]
I am unable to use the nmcli wrapper with the sub commands "nm" "con" etc. Likely a user error as python is not my forte. Could you please identify what I have done wrong below to generate the error? I am using python 3.5.2 on my NanoPi and using the nmcli in the terminal works fine.

I have done a pip3 install already and just showing below for verification sake.

`nmcli --version
nmcli tool, version 1.2.6`

```
root@NanoPi-NEO-Air:/home# pip3 install python-nmcli
Requirement already satisfied: python-nmcli in /usr/local/lib/python3.5/dist-packages (0.1.1)
root@NanoPi-NEO-Air:/home# python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nmcli import nm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'nm'
>>> import nmcli
>>> dir(nmcli)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> nmcli.con.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'nmcli' has no attribute 'con'
```

**Comment by marcelstoer** [comment]
Duhh, I did the _exact_ same thing.
